---

language: python
python: 3.6
sudo: required

services:
  - docker

# Install requirements
before_install:
  - sudo apt-get update
  - sudo apt-get install python-apt -y
  - pip install tox-travis

# Test all the scenarios against the Ansible versions defined in the tox.ini file
script:
  - sudo -E env "PATH=$PATH" tox

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
