---
dependency:
  name: galaxy
driver:
  name: docker
verifier:
  name: goss
  lint:
    name: yamllint
platforms:
  - name: consul-server-0
    groups:
      - server
  - name: consul-server-1
    groups:
      - server
  - name: consul-server-2
    groups:
      - server
  - name: client-0
    groups:
      - client
  - name: client-1
    groups:
      - client
  - name: client-2
    groups:
      - client
provisioner:
  name: ansible
  options:
    diff: True
    v: True
  playbooks:
    create: create.yml
    prepare: prepare.yml
    destroy: destroy.yml
scenario:
  name: default
